name: 2nd-manual-attempt

on:
  push:
    branches:
      - main
jobs:
  creating-mess:
    runs-on: ubuntu-latest

    steps:
      - name: Copy the repository into container
        uses: actions/checkout@v4

      - name: Check the folder
        run: pwd

      - name: Check content
        run: |
          ls -al >> folder_content.txt
          cat folder_content.txt && ls -al

      - name: create folder and files in it via script
        run: |
          chmod +x ./bash_script.sh
          sh ./bash_script.sh
              
