name: 2nd-manual-attempt

on:
  push:
    branches:
      - main
      - dev
jobs:
  creating-mess:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Show Java version
        run: java -version

      - name: checkout branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Check the folder
        run: pwd

      - name: Check content
        run: |
          ls -al >> folder_content.txt
          echo "After file created"
          ls -al

      - name: create folder and files in it via script
        run: |
          chmod +x ./bash_script.sh
          sh ./bash_script.sh
      - name: Install dependencies
        run: mvn compile
        
      - name: Build app
        run: mvn package -DshipTests

      - name: Run test
        run: mvn test
              
